services:
  - type: web
    name: signalgenv3
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0